# Κάνοντας compile το <foo>_test.c με μια υλοποίηση <foo>.c του
# συγκεκριμένου τύπου, παράγουμε ένα tets για την υλοποίηση αυτή.

PartitionedHashJoinTest = PartitionedHashJoinTest.o $(MODULES)/PartitionedHashJoin/PartitionedHashJoin.o $(MODULES)/HashTable/HashTable.o $(MODULES)/HashTable/HashTableEntry.o

# Ο βασικός κορμός του Makefile
include ../common.mk