# Λίστα με objects που περιέχει το ISSD_Project1.a library
ISSD_Project1.a_OBJS =											\
	$(MODULES)/Bitmap/Bitmap.o									\
	$(MODULES)/FileReader/FileReader.o							\
	$(MODULES)/HashTable/HashTable.o							\
	$(MODULES)/HashTable/HashTableEntry.o						\
	$(MODULES)/List/List.o										\
	$(MODULES)/List/ListNode.o									\
	$(MODULES)/PartitionedHashJoin/PartitionedHashJoin.o		\
	$(MODULES)/Relation/Relation.o								\
	$(MODULES)/RowIdRelation/RowIdRelation.o					\
	$(MODULES)/Tuple/Tuple.o		

# Ο βασικός κορμός του Makefile
include ../common.mk
